### PR TITLE
chore(release): 7.0.1

### LINKED ISSUE #120: Compatibility with Webpack 5

### PR DESCRIPTION
**Pull request by prikhi**
Hi, this PR cuts a new release using `npm run release` & should let us close #120 

You will need to run the following after merge:

```sh
git clone git@github.com:itgalaxy/robotstxt-webpack-plugin.git
cd robotstxt-webpack-plugin
git tag -m'chore(release): 7.0.1' v7.0.1
git push --follow-tags origin master
npm publish
```

### CODE REVIEW

**Comment by prikhi** [comment]
CC @alexander-akait

**Comment by prikhi** [comment]
I tried bumping some of the devDependencies while prep'ing this, but this webpack 5 change breaks the tests that try to introspect the `stats.assets`:
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#sizeonlysource-after-emit

**Comment by prikhi** [comment]
The peer dependency warning as described in https://github.com/itgalaxy/robotstxt-webpack-plugin/issues/120 & fixed in https://github.com/itgalaxy/robotstxt-webpack-plugin/pull/122

**Comment by alexander-akait** [comment]
@prikhi Please try `8.0.0` version - less deps and compatibility with webpack v5

**Comment by prikhi** [comment]
works great, thanks!

**Pull request closed without merging**
